# This is a basic workflow to help you get started with Actions

name: ChocolateRSC CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '13' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    
    - name: Build Core
      run: ant -f server/build.xml compile_core
    - name: Build Plugins
      run: ant -f server/build.xml compile_plugins
        
    - name: Build Base Client
      run: ant -f Client_Base/build.xml compile
    - uses: actions/upload-artifact@v2
      with:
        path: Client_Base/*.jar
      
    - name: Build Client Launcher
      run: ant -f PC_Launcher/build.xml compile
    - uses: actions/upload-artifact@v2
      with:
        path: PC_Launcher/*.jar
