name: ChocolateRSC CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '13' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
        
    - uses: actions/upload-artifact@v2
      with:
        name: Client
        path: Client_Base/build/libs/*.jar
    
    - uses: actions/upload-artifact@v2
      with:
        name: Client
        path: PC_Launcher/build/libs/*.jar


    - uses: actions/upload-artifact@v2
      with:
        name: Server
        path: server/build/distributions/*

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash "./Android_Client/Open RSC Android Client/gradlew" assembleDebug --stacktrace
        working-directory: "./Android_Client/Open RSC Android Client"
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: "Android_Client/Open RSC Android Client/build/outputs/apk/debug/openrsc.apk"
