name: ChocolateRSC CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '13' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'

    - name: Build Server
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: buildServer

    - name: Build Base Client
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: Client_Base:build
    - uses: actions/upload-artifact@v2
      with:
        name: Client
        path: Client_Base/build/libs/*.jar

    - name: Build Client Launcher
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: PC_Launcher:build
    - uses: actions/upload-artifact@v2
      with:
        name: Client
        path: PC_Launcher/build/libs/*.jar
